### ISSUE TITLE
Indicar ordenação sugerida

### ISSUE THREAD

**Issue by ocarneiro** [indacode/python_blogs#7]
Novos blogs devem ficar em cima ou em baixo? Ou em ordem alfabética? Ou de atualização?

**Comment by mazulo** [comment]
Por coincidência ao ver seu PR me perguntei a mesma coisa hahaha daí pensei que em ordem alfabética [a-z] seria bacana. De atualização seria mais complicado, a "métrica" que estamos usando ainda não é lá tão precisa assim.

O que vc acha?

**Comment by ocarneiro** [comment]
Concordo. Fica mais simples ordenar alfabeticamente.

Em 6 de janeiro de 2016 17:45:51 BRST, Patrick Mazulo notifications@github.com escreveu:

> Por coincidência ao ver seu PR me perguntei a mesma coisa hahaha daí
> pensei que em ordem alfabética [a-z] seria bacana. De atualização seria
> mais complicado, a "métrica" que estamos usando ainda não é lá tão
> precisa assim.
> 
> O que vc acha?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/indacode/python_blogs/issues/7#issuecomment-169437851

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
